name: over_the_air_updates_talk
description: "From fear to air: embracing over-the-air app updates."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  ai_slide_content:
    path: packages/ai_slide_content
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_deck: ^0.20.0
  flutter_deck_web_client: ^0.3.1
  notes_app:
    path: packages/notes_app
  rfw_demo:
    path: packages/rfw_demo

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/dark/
