# Copyright 2025 The Flutter Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: dart_schema_builder
description: A full-featured package used to build and validate JSON schemas in Dart.
version: 0.1.0
homepage: https://github.com/flutter/genui/packages/dart_schema_builder
license: BSD-3-Clause
issue_tracker: https://github.com/flutter/genui/issues
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  args: ^2.7.0
  characters: ^1.4.0
  collection: ^1.19.1
  decimal: ^3.2.4
  http: ^1.4.0
  intl: ^0.20.2

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  lints: ^6.0.0
  mockito: ^5.5.0
  test: ^1.25.6
